### ISSUE TITLE
AttributeError: function 'SDL_SetRelativeMouseMode' not found

### ISSUE THREAD

**Issue by alderven** [danmacnaughtan/pyxel-raycast#2]
### Error:
```
Traceback (most recent call last):
  File "D:/PROGRAMMING/temp/pyxel-raycast-master/main.py", line 52, in <module>
    _setup_api("SDL_SetRelativeMouseMode", c_int32, [c_int32])
  File "D:/PROGRAMMING/temp/pyxel-raycast-master/main.py", line 47, in _setup_api
    api = globals()[name] = getattr(_lib, name)
  File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "C:\Program Files\Python38\lib\ctypes\__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'SDL_SetRelativeMouseMode' not found
```

### Steps to reproduce:

Run [main.py](https://github.com/danmacnaughtan/pyxel-raycast/blob/master/main.py)

### Environment:

Python: 3.8
Pyxel: 1.4.3
OS: Win 10

**Comment by danmacnaughtan** [comment]
Hey, I suppose the relative mouse motion hack didn't work for the the packaged Windows binaries of the pyxel core. I was about to correct the path, but noticed yet another pyxel version was released that has rewritten the core in Rust. I decided to remove the mouse camera control all together and updated to run with Pyxel 1.5.0. Thanks!
